// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"


import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import JewelriesController from "./jewelries_controller"
application.register("jewelries", JewelriesController)

import NewMessagesController from "./new_messages_controller"
application.register("new-messages", NewMessagesController)
